[Feature]
f-lab-edu/orange-stock-ios pull request #37
Opened 2024-01-12 17:10 UTC by hogang1223

- 애플 로그인 관련 코드 AppleLoginHelper Class로 분리
- 로그인 필요 여부 판별 로직 SceneDelegate -> FavoriteStockListViewController으로 이동
- MockASAuthorizationController 파일 삭제

2024-01-13 02:27 UTC, abdul0986 commented
오... 우선 PR에 추가된 개선 리스트 내용은 굉장히 훌륭합니다. 
확장성과 유연성을 적용한 코드 개선은 필요한데요, 아주 좋은 방향입니다. CI/CD에 린트 액션을 추가한 것도 좋아요.

2024-01-13 02:32 UTC, abdul0986 commented on orange-stock-ios/orange-stock-ios/Controllers/FavoriteStockListViewController.swift
> +                self.navigationController?.setViewControllers([LoginViewController()], animated: false)
needLogin == true 일 때의 처리 로직이 여기에 들어가는 게 맞을지, 혹은 콜백 함수로 입력받아 처리하도록 커맨드 패턴으로 변형한 후에,  `verifyLoginStatus()` 를 공통 함수로 뽑는 건 어떨지 고려해보셨으면 합니다. 

로그인 상태를 체크하는 로직이 `FavoriteStockListViewController` 에만 있으면 되려나요?

2024-01-13 02:35 UTC, abdul0986 commented on orange-stock-ios/orange-stock-ios/Helpers/AppleLoginHelper.swift
> +        guard let userID = userID else { return true }
`let userID = userID` 는 좀 이상한데요, 로컬 변수를 다시 정의하는 것이라 해도 변수명이 동일하기 때문에 다소 가독성을 해칠 우려가 있어 보입니다. 변수명을 변경하거나, 혹은 코드를 다른 방식으로 재작성하는 게 좋을 듯 합니다.

2024-01-13 03:13 UTC, abdul0986 commented on orange-stock-ios/orange-stock-iosTests/AppleLoginHelperTests.swift
> +    func testLoginStatus() {
testXXX와 test_XXX 네이밍 포맷의 함수들이 혼재되어 있네요. 통일 부탁드립니다.

2024-01-16 13:48 UTC, hogang1223 commented
안녕하세요! 리뷰 주신 내용 참고하여 코드 수정했습니다!

1. 로그인 유효성 검사
로그인 유효성 검사의 경우, 
현재로서는 FavoriteListViewController에서만 사용하고 있지만,
추후 다른 기능들이 추가된다면 사용될 가능성이 높다고 생각되어
리뷰 주신 것과 같이 Command패턴을 사용하여 LoginValidator에서 로그인 유효성 검사를 할 수 있도록 수정했습니다.

2. 로그인 유효성 검사 함수의 파라미터
현재는 애플 user(String) 정보로 로그인 유효성 검사를 하고 있으나,
다른 소셜 로그인이 추가 되었을 경우,
String 형식이 아닌 Data 형식으로 저장되어 관리될 수 있다고 생각되어,
로그인 유효성 검사 시 전달받는 파라미터를 String이 아닌 Data로 수정했습니다.

2024-01-19 07:16 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Controllers/FavoriteStockListViewController.swift
> +            }
요기도 guard 구문 쓸 수 있지 않을까요? Depth가 많아져서 마음이 불편(?)하네요 ㅎㅎ

2024-01-19 07:17 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Controllers/SettingViewController.swift
> +        }
`bindPushViewController` guard로 처리를 잘 해두셨는데 `bindShowLogoutAlert()`는 guard 처리가 안되어 있네요. 적용해주세요~

2024-01-19 07:19 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Controllers/SettingViewController.swift
> +    }
이 함수 위치가 좀 이상한데요, 왜 `extension SettingViewController: UITableViewDelegate` 여기에 정의되었을까요?

2024-01-19 07:24 UTC, sqlpro commented on orange-stock-ios/orange-stock-iosTests/AppleLoginHelperTests.swift
> +        }
요건 switch 문으로 바꾸는 게 나아보여요

2024-01-19 07:26 UTC, sqlpro requested changes
몇 개 남지 않았습니다. 
3개 정도인데요, 이것만 수정하시면 LGTM 하겠습니다 :)

2024-01-19 12:39 UTC, abdul0986 approved these changes
LGTM 👍🏻

2024-01-19 12:43 UTC, abdul0986 commented
> 안녕하세요! 리뷰 주신 내용 참고하여 코드 수정했습니다!
> 
> 1. 로그인 유효성 검사
>    로그인 유효성 검사의 경우,
>    현재로서는 FavoriteListViewController에서만 사용하고 있지만,
>    추후 다른 기능들이 추가된다면 사용될 가능성이 높다고 생각되어
>    리뷰 주신 것과 같이 Command패턴을 사용하여 LoginValidator에서 로그인 유효성 검사를 할 수 있도록 수정했습니다.
> 2. 로그인 유효성 검사 함수의 파라미터
>    현재는 애플 user(String) 정보로 로그인 유효성 검사를 하고 있으나,
>    다른 소셜 로그인이 추가 되었을 경우,
>    String 형식이 아닌 Data 형식으로 저장되어 관리될 수 있다고 생각되어,
>    로그인 유효성 검사 시 전달받는 파라미터를 String이 아닌 Data로 수정했습니다.

확장성 고려하신 점 굉장히 좋은 방향입니다. 엄지 척 드립니다. 
확장성을 고려하다 보면 많은 개발자들이 현실적으로 거의 불가능한 수준까지 확장성을 고려하는 무리수를 두는 경우가 종종 있습니다. 
현실적 가능성과 지나친 확장성 사이에서 잘 판단하실 필요가 있습니다.

2024-01-19 13:15 UTC, merged