[Layout] 관심주식목록 레이아웃 구현
f-lab-edu/orange-stock-ios pull request #4
Opened 2023-11-21 12:24 UTC by hogang1223

앱의 메인화면인 관심주식목록의 레이아웃 구현했습니다.

1. 스토리보드, xib가 아닌 코드 베이스로 구현하고자 합니다.
2. 오토레이아웃을 간편하게 구현하고자 SnapKit 라이브러리를 추가하였습니다.
3. 관심 주식 목록은 tableView를 사용하여 구현하였습니다.
4. 종목명/현재가/등락/등락률은 상단에 계속 노출시키기위해 tableViewHeaderView를 사용했습니다.
5. 하단에 추가하기 버튼은 하단에 고정시키지 않기 위해 CustomTableViewCell로 구현했습니다.
6. 1개의 Cell을 위해 CustomCell을 따로 구현한 것이 낭비라고 생각이듭니다만, 다른 좋은 방법이 있을까요.. ?

2023-11-22 09:33 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/AddFavoriteStockTableViewCell.swift
> +class AddFavoriteStockTableViewCell: UITableViewCell {
클래스 성격 / 역할을 주석으로 달아주시면 좋겠습니다.

2023-11-22 09:34 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/AddFavoriteStockTableViewCell.swift
> +private extension AddFavoriteStockTableViewCell {
Extension으로 쪼갠 기준이 어떻게 되나요?

2023-11-22 09:35 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/AddFavoriteStockTableViewCell.swift
> +private extension AddFavoriteStockTableViewCell {
//MARK: - XXXXXX 주석으로 섹션을 구분해주시면 좋을 것 같습니다.

2023-11-22 11:34 UTC, hogang1223 commented on orange-stock-ios/orange-stock-ios/View/AddFavoriteStockTableViewCell.swift
> +private extension AddFavoriteStockTableViewCell {
레이아웃 구현하는 메서드들은 extension으로 분리했습니다.

2023-11-22 11:55 UTC, hogang1223 commented
@sqlpro 
리뷰 주신 주석, 마크 반영하여 commit 했습니다!

2023-11-22 12:26 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/AddFavoriteStockTableViewCell.swift
> +        button.layer.borderColor = UIColor.black.cgColor
가독성 있게 이미지, 타이틀 설정, Border 등을 구분할 수 있도록 라인을 두어 구분해주세요

2023-11-22 12:27 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListHeaderView.swift
> +        prevDayDiffRateSortButton.contentHorizontalAlignment = .right
비슷한 코드가 객체 대상만 바꾸어 가며 반복되고 있는데, 리팩토링이 필요해 보입니다.

2023-11-22 12:29 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +// MARK: UITableViewDataSource, UITableViewDelegate
```suggestion
// MARK: - UITableViewDataSource, UITableViewDelegate
```

2023-11-22 12:30 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +extension FavoriteStockListViewController: UITableViewDataSource, UITableViewDelegate {
```suggestion
// MARK: - UITableViewDataSource
extension FavoriteStockListViewController: UITableViewDataSource {
    ...
} 

// MARK: - UITableViewDelegate
extension FavoriteStockListViewController: UITableViewDelegate {
    ...
}
```

2023-11-22 12:31 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +class FavoriteStockListViewController: UIViewController {
```suggestion
final class FavoriteStockListViewController: UIViewController {
```
더이상 상속될 가능성이 없는 클래스는 항상 `final` 키워드로 선언해주길 권장드립니다.

2023-11-22 12:32 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +//        self.navigationController?.pushViewController(pushViewController, animated: true)
주석 처리된 구문은 PR 올리실 때에는 모두 제거해주세요

2023-11-22 12:33 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +    }
이거 Xcode Template Code인가요? 템플릿 코드는 꼭 필요한 것 외에는 모두 지워주시는 게 좋습니다.

2023-11-22 12:36 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListTableViewCell.swift
> +        prevDayDiffRateLabel.font = .systemFont(ofSize: 14.0)
리팩토링이 필요해 보입니다. 함수화하거나, 혹은 커스텀 레이블 클래스를 정의하는 게 좋을 것 같습니다.

2023-11-22 12:39 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListTableViewCell.swift
> +    private let prevDayDiffRateLabel = UILabel() // 등락률
이 변수들을 멤버 필드로 정의한 이유가 궁금하네요. 굳이 멤버 필드로 정의하지 않아도 될 것 같아 보입니다.

2023-11-22 12:43 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +        }
이 부분은 삼항 연산자로 처리하는 게 더 낫지 않을까요? guard의 적절한 사용 예는 아닌 듯 한데 guard로 처리한 이유가 궁금합니다.

2023-11-22 12:44 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
구문이 if ~ else로 길게 나누어지면서 가독성이 안 좋아지는데, 함수로 더 쪼개어 가독성을 높였으면 좋겠습니다.

2023-11-22 12:44 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +        return headerView
여기도 guard가 사용된 이유가 궁금하네요.

2023-11-22 12:46 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +        if indexPath.row == 30 {
마지막 인덱스가 30으로 고정인가요?

2023-11-22 12:47 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +            guard let cell = tableView.dequeueReusableCell(withIdentifier: "FavoriteStockListTableViewCell", for: indexPath) as? FavoriteStockListTableViewCell else { return UITableViewCell() }
`if let`, `guard let` 등의 구문이 긴 경우에는 줄 바꿈 하고 한 칸 들여 쓰는 것이 좋습니다.

2023-11-22 12:52 UTC, sqlpro reviewed
전체적으로 `setSubViews()`와 `layout()` 함수가 레이아웃을 전담하고 있는데, 코드가 길어서 함수가 verbose합니다. 세부 단위별로 이해하기 쉽도록 작은 단위의 함수로 나눌 필요가 있습니다. 

`setSubViews()`와 `layout()`가 역할을 나눌 수 있도록 UI 요소를 멤버 필드로 선언해 두셨는데, 굳이 멤버 필드로 관리해야 할 이유가 보이지 않아 개선이 필요할 듯 합니다.

2023-11-22 13:09 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/AddFavoriteStockTableViewCell.swift
> +class AddFavoriteStockTableViewCell: UITableViewCell {
```suggestion
final class AddFavoriteStockTableViewCell: UITableViewCell {
```

2023-11-22 13:10 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/AddFavoriteStockTableViewCell.swift
> +class AddFavoriteStockTableViewCell: UITableViewCell {
`AddFavoriteStockTableViewCell`는 동사로 시작하고 있는데, 일반적으로 동사는 함수의 네이밍에 사용되기 때문에 클래스의 이름으로는 부적절합니다. 명사 형태의 적절한 네이밍을 고려해서 적용해주세요

2023-11-22 13:21 UTC, sqlpro reviewed
추가하기 셀 하나 때문에 CustomTableViewCell을 정의하는 것이 다소 비효율적으로 보일 수도 있지만, 지금 구조에서는 딱히 문제는 없을 것 같습니다. 추후 앱이 확장된다면 커스텀 셀이 여러 곳에서 사용될 수도 있을테고요.

2023-11-28 13:23 UTC, hogang1223 commented
@sqlpro  리뷰 주신 부분 리팩토링 했습니다.

### FavoriteStockListTableViewCell
1. StockLabel
StockLabel이라는 커스텀 Label 클래스를 생성했습니다.
enum으로 종목의 어떤 정보를 표기할건지 정의했는데,
Label 클래스가 stock의 정보를 굳이 갖게 할 필요가 있는지 의심이 듭니다.

2. func addStockLabelsConstraint(_ views: [StockLabel])
label 변수를 stockLabels라는 배열에 넣어서, 
stockLabels를 멤버 변수를 사용하다보니
인덱스로 원소들을 직접 호출해서 레이아웃을 잡는 코드가 나타나버렸습니다.
이렇게 하지 않으려면 역시 label들을 멤버변수로 사용하는게 좋은걸까 생각이 드는데
그렇게되면 레이아웃 함수의 코드가 너무 길어지는 것 같다는 생각이 들어서 고민이 됩니다.
이 부분에 대해서 의견 부탁드립니다.

2023-12-01 08:31 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Entities/Stock.swift
> +                return Color.stockDown
```suggestion
            case .upperLimit, .increase:
                return .stockUp
            case .stability:
                return .basic
            case .lowerLimit, .decrease:
                return .stockDown
```

타입을 충분히 예상할 수 있을 때에는 (지금의 경우엔 리턴 타입이 Fix되어 있으니까요) 
가독성을 위해 타입을 생략하는 것이 좋습니다.

2023-12-01 08:37 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockAdditionTableViewCell.swift
> +    }
생략 가능한 타입 명은 모두 생략해주시면 좋을 듯요 
ex) 
```
button.tintColor =.basic
```

2023-12-01 14:59 UTC, hogang1223 commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +        else { return UITableViewCell() }
```swift
cell.stock(self.favoriteStockList[indexPath.row])
``` 
FavoriteStockListTableViewCell의 `func stock(_ stock: Stock?)` method에 접근하기 위해서 Guard을 사용하였습니다.

2023-12-01 15:23 UTC, hogang1223 commented
리뷰주신 부분 수정했습니다!

2023-12-01 16:03 UTC, sqlpro requested changes
코드가 전반적으로 많이 깔끔해졌네요. 좋습니다. :) 
다만 타입 제거, Documentation을 위한 주석 추가 등의 작업이 더 필요해 보입니다.

2023-12-01 16:06 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +    func setNavtaionBar() {
함수명에 오타가 있는 것 같습니다.

2023-12-01 23:24 UTC, hogang1223 commented on orange-stock-ios/orange-stock-ios/View/FavoriteStockListViewController.swift
> +        else { return UITableViewCell() }
FavoriteStockListTableViewCell에 Stock 객체를 전달하기 위해 `func stock(_ stock: Stock?)` 메서드를 정의해놓았는데,
UITableViewCell에는 stock이라는 메서드가 없기 때문에 위의 메서드를 호출하고자 하면, 컴파일 오류가 발생하게 되어 guard문을 사용했습니다.

guard 문 대신 아래와 같이 사용하는게 나을까요??
```swift
let cell = tableView.dequeueReusableCell(withIdentifier: .stockListTableViewCell, for: indexPath) as? FavoriteStockListTableViewCell
cell?.stock(self.favoriteStockList[indexPath.row])
return cell ?? UITableViewCell()
```

2023-12-03 01:25 UTC, merged