[Feature] 설정 기능 리팩토링
f-lab-edu/orange-stock-ios pull request #40
Opened 2024-01-23 11:55 UTC by hogang1223

안녕하세요!

설정 기능 리팩토링 했습니다.
지난 멘토링 시간에 말씀 주신 것처럼 Enum을 사용한 것 중 함수형 프로그래밍으로 바꿀 수 있는 부분들을 수정했습니다.
- SettingViewModel: 기존에 테이블 뷰 관련 정보를 enum으로 선언하여 사용했으나, protocol과 struct로 변경했습니다.
- AppearanceType: 멘토링 시간에 예시로 작성해 주신 코드에서 AppearanceSetting property를 추가했습니다.
OCP에 위배되나 
1.화면설정타입이 3가지에서 추가될 확률이 적다는 점과 
2.AppearanceType의 rawValue를 UserDefaults에 저장, 사용하여 AppearanceType와 AppearanceSetting간의 결합도가 높아
어차피 써야할 switch case문이라면, enum에 property로 선언하는게 합리적이라고 생각했습니다.
- AppearanceManager: 기존엔 싱글톤 클래스로 사용하고 있었으나, 현재 사용하는 시점이 앱 실행시, 화면 설정시, 두 곳 뿐인데다가, 따로 변수를 두어 값을 저장해야할 필요가 없다고 판단되어 구조체로 변경하였습니다.

2024-01-25 01:37 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Controllers/AppearanceSettingViewController.swift
>      override func viewDidLoad() {
viewDidLoad()는 지워도 되지 않을까요?

2024-01-25 10:22 UTC, hogang1223 commented on orange-stock-ios/orange-stock-ios/Controllers/AppearanceSettingViewController.swift
>      override func viewDidLoad() {
앗 viewDidLoad() 에서 UI 세팅하는 layout() 함수를 호출하고 있습니다! 🥲

2024-01-26 01:08 UTC, sqlpro requested changes
코드가 훨씬 깔끔해졌네요. 좋습니다. 
개별 클래스에서 보일러플레이트 처럼 쓰고 있는 함수 들만 Protocol 기반으로 일관성 잡아주면 
상당히 완성도가 높아질 것 같습니다. 

ex) `setNavigation()`, `setBackgroundColor()` 등등

2024-01-26 01:08 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Controllers/SettingViewController.swift
> +        constraintTableView()
이 3개의 function은 함께 붙어 다니는 경우가 많은 것 같은데, 별도의 레이아웃 관련 프로토콜 하나를 정의하고 그걸 구현하기 위한 익스텐션으로 처리하는 게 어떨까요? 일관성을 갖추는 데에 도움이 될 것 같습니다.

2024-01-26 01:08 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Managers/AppearanceManager.swift
> +}
👍🏻

2024-01-26 01:08 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/Controllers/AppearanceSettingViewController.swift
>      override func viewDidLoad() {
엇 PR에서는 해당 코드가 숨김 처리되어 있어서 함수 안에 아무 것도 없는 줄 알았네요. OK~ 👍🏻

2024-01-30 14:14 UTC, sqlpro requested changes
다 좋은데 제일 마지막 부분에서 걸리네요. 
얼렁 수정해 보도록 합시다!!! :)

2024-01-30 14:14 UTC, sqlpro commented on orange-stock-ios/orange-stock-ios/ViewModels/SettingViewModel.swift
>          }
이 부분이 Demeter's Law에 어긋납니다. rowInfo, 그러니까 SettingAppearanceRow.type의 값이 무엇인지를 `SettingViewModel` 에서 직접 평가해서 if ~ else 로직을 작성하면 SettingAppearanceRow과의 결합도가 높아지는 결과가 만들어지거든요. 

이건 rowInfo.isLogoutType() 같은 메소드를 만들어서 결과만 리턴받는 식으로 변경해서, 
다른 객체의 내부 속성에 개입하는 구조를 제거하는 것이 좋습니다.

2024-02-02 10:21 UTC, hogang1223 commented on orange-stock-ios/orange-stock-ios/ViewModels/SettingViewModel.swift
>          }
```
protocol SettingTableViewRow {
    var type: SettingTableViewType { get }
    var title: String { get }
    var accessory: UITableViewCell.AccessoryType { get }
    var pushViewController: UIViewController? { get }
    func didSelected(with viewModel: SettingViewModel)
}
```
이렇게 수정하면 viewModel과의 결합도가 높아지게 되는걸까요... ?

2024-02-03 01:00 UTC, abdul0986 approved these changes
LGTM

2024-02-07 10:10 UTC, merged